# DevSecOps Workflow Definition
# This workflow is triggered on every push to the repository

# Test 2

name: DevGuard-Workflow

on:
  workflow_dispatch:
  push:

permissions: {}

jobs:
  api-pipeline:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/full-nix.yml
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      allow-failure: true
      nix-target-amd64: devguard-amd64
      nix-target-arm64: devguard-arm64
      nix-version: '2.34.4'
      nix-impure: "true"
      image-name: ghcr.io/${{ github.repository }}
      devguard-asset-name: testorg/projects/emptybranch/assets/devguard-tag-test
      devguard-api-url: https://swimwear-exemplary-blinking.ngrok-free.dev
      devguard-web-ui: http://localhost:3000
      fail-on-cvss: never
      fail-on-risk: never
      nix-cache-substituter: https://nix.garage.l3montree.cloud
      nix-cache-public-key: nix.garage.l3montree.cloud:MGlzfPQKA91/zxw91CN+GP7NpjAAwmKvWXlDYgeeI8k=
      nix-cache-s3-bucket: nix
      nix-cache-region: garage
    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
